<a href="https://colab.research.google.com/github/Manoj-Kumar-Ejjada-AI/MathforDS/blob/math_manoj/Linear%20Equations/LinearSystems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# !pip install utils

  Preparing metadata (setup.py) ... done
  Created wheel for utils: filename=utils-1.0.2-py2.py3-none-any.whl size=13906 sha256=2a407f7079d6980c4bedec31710d9667cb316e7fead176f6d7f5f5652df09dfa
  Stored in directory: /root/.cache/pip/wheels/b6/a1/81/1036477786ae0e17b522f6f5a838f9bc4288d1016fc5d0e1ec
Successfully built utils


In [3]:
import numpy as np
import matplotlib.pyplot as plt


<a name='1.1'></a>
### 1.1 - System of Linear Equations

A **system of linear equations** (or **linear system**) is a collection of one or more linear equations involving the same variables. For example:


$$
\begin{cases}
-x_1+3x_2=7, \\ 3x_1+2x_2=1, \end{cases}\tag{1}
$$

is a system of two equations with two unknown variables $x_1$ and $x_2$. **To solve** a system of linear equations means to find values for the variables $x_1$ and $x_2$ such that all of its equations are simultaneously satisfied.

A linear system is **singular** if it has no unique solution, and otherwise, it is said to be **non-singular**.

In [4]:
A = np.array([[-1,3],[3,2]],dtype = np.dtype(float))
b = np.array([7,1],dtype = np.dtype(float))
print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[-1.  3.]
 [ 3.  2.]]

Array b:
[7. 1.]


In [5]:
# Dimensions
print(A.shape)  # column, rows
print(b.shape)

(2, 2)
(2,)


In [6]:
sol = np.linalg.solve(A,b)
print(sol)
print("Solution shape is: ",sol.shape)

[-1.  2.]
Solution shape is:  (2,)


In [7]:
detA = np.linalg.det(A)
print("Determinent of A is:", detA)

Determinent of A is: -11.000000000000002


In [8]:
d = np.linalg.det(A)

print(f"Determinant of matrix A: {d:.2f}")

Determinant of matrix A: -11.00


<a name='2.1'></a>
### 2.1 - Representation of the system as a matrix

Before you visualize the system $(1)$, you would want to represent the system in a matrix with the form:

$$
\begin{bmatrix}
-1 & 3 & 7 \\
3 & 2 & 1
\end{bmatrix}
$$

To do this, you can either create a new matrix with these values or horizontally stack the $A$ and $b$ matrices you created earlier. Note that the `np.hstack()` function will require you to reshape array $b$ before it is stacked, as its current shape is $(2,)$. The code below includes the `.reshape((2, 1))` command to allow the horizontal stack to be completed.

In [9]:
A_System = np.hstack((A,b.reshape((2,1))))
print(A_System)

[[-1.  3.  7.]
 [ 3.  2.  1.]]


## In case you don't understand reshape, see below cell, else skip

In [22]:
print("b is: ",b)
print(f"Shape of b is: {b.shape}")  # 1 value represents only columns 1-D array
print("Reshaping b to (2,1): ")
print(b.reshape(2,1))
print("Shape of Reshaped b: ",b.reshape(2,1).shape)  # 2 represents rows and columns
a_test = np.array([[1,2,3]])
print(a_test)
print("Shape off a_test is:", a_test.shape)  # 1 row, 3 columns

b is:  [7. 1.]
Shape of b is: (2,)
Reshaping b to (2,1): 
[[7.]
 [1.]]
Shape of Reshaped b:  (2, 1)
[[1 2 3]]
Shape off a_test is: (1, 3)


In [26]:
# plt.plot(A_System)

<a name='3'></a>
## 3 - System of Linear Equations with No Solutions

Given another system of linear equations:

$$
\begin{cases}
-x_1+3x_2=7, \\ 3x_1-9x_2=1, \end{cases}\tag{2}
$$

Let's find the determinant of the corresponding matrix.

In [27]:
a2 = np.array([[-1,3],[3,-9]])
print(a2)

[[-1  3]
 [ 3 -9]]


In [28]:
det_A2 = np.linalg.det(a2)
print(det_A2)

0.0


### Hence it is singular