In [2]:
import numpy as np

In [2]:
one_dimensional_arr = np.array([10, 12])
print(one_dimensional_arr)

[10 12]


In [4]:
b = np.arange(20)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [6]:
c = np.arange(2,20,3)
print(c)

[ 2  5  8 11 14 17]


In [10]:
d = np.linspace(5,100,20)
print(d)

[  5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.  70.
  75.  80.  85.  90.  95. 100.]


In [12]:
e = np.linspace(10,35,10, dtype=int)
print(e)

[10 12 15 18 21 23 26 29 32 35]


In [13]:
f = np.arange(10,35,10,dtype=int)
print(f)


[10 20 30]


In [15]:
g = np.array(['Welcome to Manoj`s Github Repo'])
print(g)
print(g.dtype)

['Welcome to Manoj`s Github Repo']
<U30


In [16]:
ones_array = np.ones(5)
print(ones_array)

[1. 1. 1. 1. 1.]


In [5]:
zeroes_array = np.zeros([5])
print(zeroes_array)

[0. 0. 0. 0. 0.]


## np.empty() in NumPy is used to create a new array of a given shape and data type without initializing its values.
This means the array will contain arbitrary (garbage) values that were already present in the allocated memory.

In [24]:
empt_arr = np.empty(3)
print(empt_arr)

[10. 22. 35.]


## random.rand return a new array of shape 3 with random numbers between 0 and 1.

In [9]:
random_arr = np.random.rand(4)
print(random_arr)

[0.26092493 0.11445987 0.41711834 0.88079286]


In [10]:
two_dim_arr = np.array([[1,2,3], [4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [14]:
one_dim_arr = np.array([1,2,3,4,5,6])
two_dim_arr = np.reshape(one_dim_arr, (2,3))
three_dim_arrray = np.reshape(one_dim_arr, (2,3,1))
print(two_dim_arr)
print(three_dim_arrray)

[[1 2 3]
 [4 5 6]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [17]:
# To get 2,
access_ele_in_three_dim = three_dim_arrray[0,1,0]
print(access_ele_in_three_dim)

2


In [18]:
three_dim_arrray.ndim

3

In [19]:
three_dim_arrray.shape

(2, 3, 1)

In [21]:
# Number of elements
three_dim_arrray.size

6

In [24]:
list1 = [2,4,6]
list2 = [1,3,5]

# General addition of lists in python
print(list1+list2)


arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays elementwise
multiplication = arr_1 * arr_2
print(multiplication)

[2, 4, 6, 1, 3, 5]
[ 3  7 11]
[1 1 1]
[ 2 12 30]


## 3.1 - Multiplying vector with a scalar (broadcasting) ##
# Suppose you need to convert miles to kilometers. To do so, you can use the NumPy array functions that you`ve learned so far. You can do this by carrying out an operation between an array (miles) and a single number (the conversion rate which is a scalar). Since, 1 mile = 1.6 km, NumPy computes each multiplication within each cell.

# This concept is called **broadcasting**, which allows you to perform operations specifically on arrays of different shapes.

In [29]:
miles = np.array([1, 2])
km = miles * 1.6
print(km)

[1.6 3.2]


In [30]:
miles = np.array([[1, 2],[3,4]])
km = miles * 1.6
print(km)

[[1.6 3.2]
 [4.8 6.4]]


In [31]:
# Select the third element of the array. Remember the counting starts from 0.
a = ([1, 2, 3, 4, 5])
print(a[2])

# Select the first element of the array.
print(a[0])

3
1


For multidimensional arrays of shape `n`, to index a specific element, you must input `n` indices, one for each dimension.

In [34]:
two_dim_arr = np.array(([1,2,3],
                        [4,5,6],
                        [7,8,9]))
# To access 3
print(two_dim_arr[0,2])

3


<a name='4-2'></a>
## 4.2 - Slicing ##
Slicing gives you a sublist of elements that you specify from the array. The slice notation specifies a start and end value, and copies the list from start up to but not including the end (end-exclusive).

The syntax is:

`array[start:end:step]`

If no value is passed to start, it is assumed `start = 0`, if no value is passed for end, it is assumed that `end = length of array` and if no value is passed to step, it is assumed `step = 1`.


In [39]:
# Slice the array a to get the array [2,3,4]
# Slice the array a to get the array [1,2,3]
# Slice the array a to get the array [3,4,5]
# Slice the array a to get the array [1,3,5]
# Note that a == a[:] == a[::]
print(a[1:4])
print(a[:3])
print(a[2:])
print(a[::2])
print(a == a[:] == a[::])

[2, 3, 4]
[1, 2, 3]
[3, 4, 5]
[1, 3, 5]
True


In [43]:
# Slice the two_dim array to get the first two rows

print(two_dim_arr[:2])  # same as [:2,:]

[[1 2 3]
 [4 5 6]]


In [48]:
# Similarily, slice the two_dim array to get the last two rows
print(two_dim_arr.shape[0])
print(two_dim_arr[1:])
# OR
print(two_dim_arr[two_dim_arr.shape[0]-2:])

3
[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]


In [51]:
# Similarily, slice the two_dim array to get the last two columns

print(two_dim_arr[:,1:])

[[2 3]
 [5 6]
 [8 9]]


<a name='5'></a>
# 5 - Stacking #
Finally, stacking is a feature of NumPy that leads to increased customization of arrays. It means to join two or more arrays, either horizontally or vertically, meaning that it is done along a new axis.

- `np.vstack()` - stacks vertically
- `np.hstack()` - stacks horizontally
- `np.hsplit()` - splits an array into several smaller arrays

In [52]:
a1 = np.array([[1,1],
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [53]:
# Stack the arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)


[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [54]:
# Stack the arrays vertically
vert_stack = np.hstack((a1, a2))
print(vert_stack)


[[1 1 3 3]
 [2 2 4 4]]


In [55]:
# Stack the arrays vertically
vert_stack = np.hsplit(a1,2)
print(vert_stack)


[array([[1],
       [2]]), array([[1],
       [2]])]
