<a href="https://colab.research.google.com/github/Manoj-Kumar-Ejjada-AI/MathforDS/blob/math_manoj/Linear%20Equations/LinearSystems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
!pip install utils

In [10]:
import numpy as np
import matplotlib.pyplot as plt


<a name='1.1'></a>
### 1.1 - System of Linear Equations

A **system of linear equations** (or **linear system**) is a collection of one or more linear equations involving the same variables. For example:


$$
\begin{cases}
-x_1+3x_2=7, \\ 3x_1+2x_2=1, \end{cases}\tag{1}
$$

is a system of two equations with two unknown variables $x_1$ and $x_2$. **To solve** a system of linear equations means to find values for the variables $x_1$ and $x_2$ such that all of its equations are simultaneously satisfied.

A linear system is **singular** if it has no unique solution, and otherwise, it is said to be **non-singular**.

In [24]:
A = np.array([[-1,3],[3,2]],dtype = np.dtype(float))
b = np.array([7,1],dtype = np.dtype(float))
print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[-1.  3.]
 [ 3.  2.]]

Array b:
[7. 1.]


In [17]:
# Dimensions
print(A.shape)  # column, rows
print(b.shape)

(2, 2)
(2,)


In [22]:
sol = np.linalg.solve(A,b)
print(sol)
print("Solution shape is: ",sol.shape)

[-1.  2.]
Solution shape is:  (2,)


In [28]:
detA = np.linalg.det(A)
print("Determinent of A is:", detA)

Determinent of A is: -11.000000000000002


In [29]:
d = np.linalg.det(A)

print(f"Determinant of matrix A: {d:.2f}")

Determinant of matrix A: -11.00


<a name='2.1'></a>
### 2.1 - Representation of the system as a matrix

Before you visualize the system $(1)$, you would want to represent the system in a matrix with the form:

$$
\begin{bmatrix}
-1 & 3 & 7 \\
3 & 2 & 1
\end{bmatrix}
$$

To do this, you can either create a new matrix with these values or horizontally stack the $A$ and $b$ matrices you created earlier. Note that the `np.hstack()` function will require you to reshape array $b$ before it is stacked, as its current shape is $(2,)$. The code below includes the `.reshape((2, 1))` command to allow the horizontal stack to be completed.

In [33]:
A_System = np.hstack((A,b.reshape((2,1))))
print(A_System)

[[-1.  3.  7.]
 [ 3.  2.  1.]]
