In [101]:
import numpy

In [102]:
import numpy as np
import math

class w2_unittest:
  def test_matrix(self,target_A, target_b):

    successful_cases = 0
    failed_cases = []

    test_cases = [
        {
            "name": "default_check",
            "expected": {
                "A": np.array(
                    [[2, -1, 1, 1], [1, 2, -1, -1], [-1, 2, 2, 2], [1, -1, 2, 1]]
                ),
                "b": np.array([6, 3, 14, 8]),
            },
        },
    ]

    for test_case in test_cases:

        try:
            assert target_A.shape == test_case["expected"]["A"].shape
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["A"].shape,
                    "got": target_A.shape,
                }
            )
            print(
                f"Wrong shape of matrix A. \n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )
            break

        try:
            assert np.allclose(target_A, test_case["expected"]["A"])
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": np.nonzero(
                        np.logical_not(np.isclose(target_A, test_case["expected"]["A"]))
                    ),
                    "got": target_A,
                }
            )
            print(
                f"Wrong matrix of coefficients corresponding to the system of linear equations.\nCheck the coefficient in the row {failed_cases[-1].get('expected')[0][0] + 1}, column {failed_cases[-1].get('expected')[1][0] + 1}."
            )

        try:
            assert target_b.shape == test_case["expected"]["b"].shape
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["b"].shape,
                    "got": target_b.shape,
                }
            )
            print(
                f"Wrong shape of vector b. \n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )
            break

        try:
            assert np.allclose(target_b, test_case["expected"]["b"])
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": np.nonzero(
                        np.logical_not(np.isclose(target_b, test_case["expected"]["b"]))
                    ),
                    "got": target_b,
                }
            )
            print(
                f"Wrong vector of free coefficients corresponding to the system of linear equations.\nCheck element {failed_cases[-1].get('expected')[0][0] + 1} in the vector b."
            )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")
  def test_det_and_solution_scipy(self, target_d, target_x):

    successful_cases = 0
    failed_cases = []

    test_cases = [
        {"name": "default_check", "expected": {
            "d": -17.0,
            "x": np.array([2, 3, 4, 1])},
        },
    ]

    for test_case in test_cases:

        try:
            assert math.isclose(target_d, test_case["expected"]["d"], abs_tol=1e-04)
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["d"],
                    "got": target_d,
                }
            )
            print(
                f"Wrong determinant of matrix A.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert target_x.shape == test_case["expected"]["x"].shape
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["x"].shape,
                    "got": target_x.shape,
                }
            )
            print(
                f"Wrong shape of the solution vector. \n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )
            break

        try:
            assert np.allclose(target_x, test_case["expected"]["x"])
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["x"],
                    "got": target_x,
                }
            )
            print(
                f"Wrong solution vector.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")


  def test_elementary_operations(self,target_MultiplyRow, target_AddRows, target_SwapRows):
    successful_cases = 0
    failed_cases = []

    test_cases = [
        {
            "name": "default_check",
            "input": {
                "A": np.array(
                    [[1, -2, 3, -4], [-5, 6, -7, 8], [-4, 3, -2, 1], [8, -7, 6, -5]]
                )
            },
            "expected": {
                "A_MultiplyRow": np.array(
                    [[1, -2, 3, -4], [-5, 6, -7, 8], [8, -6, 4, -2], [8, -7, 6, -5]]
                ),
                "A_AddRows": np.array(
                    [[1, -2, 3, -4], [-5, 6, -7, 8], [0, -5, 10, -15], [8, -7, 6, -5]]
                ),
                "A_SwapRows": np.array(
                    [[-4, 3, -2, 1], [-5, 6, -7, 8], [1, -2, 3, -4], [8, -7, 6, -5]]
                ),
            },
        },
    ]

    for test_case in test_cases:
        result_MultiplyRow = target_MultiplyRow(test_case["input"]["A"], 2, -2)
        result_AddRows = target_AddRows(test_case["input"]["A"], 0, 2, 4)
        result_SwapRows = target_SwapRows(test_case["input"]["A"], 0, 2)

        try:
            assert (
                result_MultiplyRow.shape == test_case["expected"]["A_MultiplyRow"].shape
            )
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["A_MultiplyRow"].shape,
                    "got": result_MultiplyRow.shape,
                }
            )
            print(
                f"Wrong shape of the output matrix. Check MultiplyRow function. \n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert np.allclose(
                result_MultiplyRow, test_case["expected"]["A_MultiplyRow"]
            )
            successful_cases += 1

        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["A_MultiplyRow"],
                    "got": result_MultiplyRow,
                }
            )
            print(
                f"Wrong output matrix. Check MultiplyRow function. \n\tExpected: \n{failed_cases[-1].get('expected')}\n\tGot: \n{failed_cases[-1].get('got')}"
            )

        try:
            assert result_AddRows.shape == test_case["expected"]["A_AddRows"].shape
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["A_AddRows"].shape,
                    "got": result_AddRows.shape,
                }
            )
            print(
                f"Wrong shape of the output matrix. Check AddRows function. \n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert np.allclose(result_AddRows, test_case["expected"]["A_AddRows"])
            successful_cases += 1

        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["A_AddRows"],
                    "got": result_AddRows,
                }
            )
            print(
                f"Wrong output matrix. Check AddRows function. \n\tExpected: \n{failed_cases[-1].get('expected')}\n\tGot: \n{failed_cases[-1].get('got')}"
            )

        try:
            assert result_SwapRows.shape == test_case["expected"]["A_SwapRows"].shape
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["A_SwapRows"].shape,
                    "got": result_SwapRows.shape,
                }
            )
            print(
                f"Wrong shape of the output matrix. Check SwapRows function. \n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert np.allclose(result_SwapRows, test_case["expected"]["A_SwapRows"])
            successful_cases += 1

        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["A_SwapRows"],
                    "got": result_SwapRows,
                }
            )
            print(
                f"Wrong output matrix. Check SwapRows function. \n\tExpected: \n{failed_cases[-1].get('expected')}\n\tGot: \n{failed_cases[-1].get('got')}"
            )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")


  def test_augmented_to_ref(self,target):

    successful_cases = 0
    failed_cases = []

    test_cases = [
        {
            "name": "default_check",
            "input": {
                "A": np.array(
                    [[2, -1, 1, 1], [1, 2, -1, -1], [-1, 2, 2, 2], [1, -1, 2, 1]]
                ),
                "b": np.array([6, 3, 14, 8]),
            },
            "expected": {
                "A_ref": np.array(
                    [
                        [1, 2, -1, -1, 3],
                        [0, 1, 4, 3, 22],
                        [0, 0, 1, 3, 7],
                        [0, 0, 0, 1, 1],
                    ]
                )
            },
        },
        {
            "name": "identity_matrix",
            "input": {
                "A": np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]),
                "b": np.array([1, 1, 1, 1]),
            },
            "expected": {
                "A_ref": np.array(
                    [
                        [0, 1, 0, 0, 1],
                        [0, 0, 1, 1, 2],
                        [2, -1, 1, -2, 0],
                        [0, 0, 0, -1, 0],
                    ]
                )
            },
        },
    ]

    for test_case in test_cases:
        result = target(test_case["input"]["A"], test_case["input"]["b"])

        try:
            assert result.shape == test_case["expected"]["A_ref"].shape
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["A_ref"].shape,
                    "got": result.shape,
                }
            )
            print(
                f"Test case \"{failed_cases[-1].get('name')}\". Wrong shape of the output matrix. Check horizontal stack of matrix A and vector b. \n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert np.allclose(result, test_case["expected"]["A_ref"])
            successful_cases += 1

        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["A_ref"],
                    "got": result,
                }
            )
            print(
                f"Test case \"{failed_cases[-1].get('name')}\". Wrong output matrix. Check row reduction operations. \n\tExpected: \n{failed_cases[-1].get('expected')}\n\tGot: \n{failed_cases[-1].get('got')}"
            )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")


  def test_solution_elimination(self,target_x_1, target_x_2, target_x_3, target_x_4):

    successful_cases = 0
    failed_cases = []

    test_cases = [
        {
            "name": "default_check",
            "expected": {"x_1": 2, "x_2": 3, "x_3": 4, "x_4": 1},
        },
    ]

    for test_case in test_cases:

        for i, target_x_i in enumerate([target_x_1, target_x_2, target_x_3, target_x_4]):
            try:
                assert target_x_i == test_case["expected"]["x_" + str(i+1)]
                successful_cases += 1
            except:
                failed_cases.append(
                    {
                        "name": test_case["name"],
                        "expected": test_case["expected"]["x_" + str(i+1)],
                        "got": target_x_i,
                    }
                )
                print(
                    f"Wrong value of x_{(i+1)}.\n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
                )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")


  def test_ref_to_diagonal(self,target):

    successful_cases = 0
    failed_cases = []

    test_cases = [
        {
            "name": "default_check",
            "input": {
                "A_ref": np.array(
                    [
                        [1, 2, -1, -1, 3],
                        [0, 1, 4, 3, 22],
                        [0, 0, 1, 3, 7],
                        [0, 0, 0, 1, 1],
                    ]
                )
            },
            "expected": {
                "A_diag": np.array(
                    [
                        [1, 0, 0, 0, 2],
                        [0, 1, 0, 0, 3],
                        [0, 0, 1, 0, 4],
                        [0, 0, 0, 1, 1],
                    ]
                )
            },
        },
        {
            "name": "identity_matrix",
            "input": {
                "A_ref": np.array(
                    [[1, 0, 0, 0, 1], [0, 1, 0, 0, 1], [0, 0, 1, 0, 1], [0, 0, 0, 1, 1]]
                )
            },
            "expected": {
                "A_diag": np.array(
                    [
                        [1, -2, 9, -20, -12],
                        [0, 1, -4, 9, 6],
                        [0, 0, 1, -3, -2],
                        [0, 0, 0, 1, 1],
                    ]
                )
            },
        },
    ]

    for test_case in test_cases:
        result = target(test_case["input"]["A_ref"])

        try:
            assert result.shape == test_case["expected"]["A_diag"].shape
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["A_diag"].shape,
                    "got": result.shape,
                }
            )
            print(
                f"Test case \"{failed_cases[-1].get('name')}\". Wrong shape of the output matrix. \n\tExpected: {failed_cases[-1].get('expected')}.\n\tGot: {failed_cases[-1].get('got')}."
            )

        try:
            assert np.allclose(result, test_case["expected"]["A_diag"])
            successful_cases += 1

        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"]["A_diag"],
                    "got": result,
                }
            )
            print(
                f"Test case \"{failed_cases[-1].get('name')}\". Wrong output matrix. Check row reduction operations. \n\tExpected: \n{failed_cases[-1].get('expected')}\n\tGot: \n{failed_cases[-1].get('got')}"
            )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")

In [103]:
test = w2_unittest()

<a name='1'></a>
## 1 - System of Linear Equations and Corresponding `NumPy` Arrays

Matrices can be used to solve systems of equations. But first, you need to represent the system using matrices. Given the following system of linear equations:

$$\begin{cases}
2x_1-x_2+x_3+x_4=6, \\ x_1+2x_2-x_3-x_4=3, \\ -x_1+2x_2+2x_3+2x_4=14, \\ x_1-x_2+2x_3+x_4=8, \end{cases}\tag{1}$$

you will construct matrix $A$, where each row represents one equation in the system and each column represents a variable $x_1$, $x_2$, $x_3$, $x_4$. The free coefficients from the right sides of the equations you will put into vector $b$.

Constructing matrix $A$ and vector $b$ corresponding to the system of linear equations $(1)$.

In [104]:
A = np.array([
    [2,-1,1,1],
    [1,2,-1,-1],
    [-1,2,2,2],
    [1,-1,2,1]
    ],dtype = np.dtype(float))
b = np.array([6,3,14,8])

In [105]:
#Testing
test.test_matrix(A,b)

 All tests passed


<a name='2'></a>
## 2 - Solution for the System of Equations with `NumPy` Linear Algebra Package

A system of four linear equations with four unknown variables has a unique solution if and only if the determinant of the corresponding matrix of coefficients is not equal to zero. `NumPy` provides quick and reliable ways to calculate the determinant of a square matrix and also to solve the system of linear equations.

In [106]:
# Finding solution and Determinant



detA = np.linalg.det(A)
# print(detA)

solution_1 = np.linalg.solve(A,b)
# print(solution_1)

test.test_det_and_solution_scipy(detA,solution_1)

 All tests passed


<a name='3'></a>
## 3 - Elementary Operations and Row Reduction

Even though the contemporary packages allow to find the solution with one line of the code, performing required algebraic operations manually helps to build foundations which are necessary for deep understanding of the machine learning algorithms.

Lets solve the system of linear equations algebraically using row reduction. It involves combination of the equations using elementary operations, eliminaring as many variables as possible for each equation. There are three valid operations which can be performed to bring the system of equations to equivalent one (with the same solutions):

- Multiply any row by non-zero number
- Add two rows and exchange one of the original rows with the result of the addition
- Swap rows

In [107]:
def MultiplyRow(M,row_num,multiply_by):
  M_new = M.copy()
  M_new[row_num] = M[row_num]*multiply_by
  return M_new
def AddRow(M,Row1_Num,Row2_Num, Multiply_row1by):
  M_New = M.copy()
  M_New[Row2_Num] = M[Row1_Num] * Multiply_row1by+ M[Row2_Num]
  return M_New
def SwapRows(M,Row1_Num,Row2_Num):
  M_new = M.copy()
  M_new[[Row1_Num,Row2_Num]] = M[[Row2_Num,Row1_Num]]
  return M_new
test.test_elementary_operations(MultiplyRow,AddRow,SwapRows)
# print(MultiplyRow(A,1,2))

# print(A[1])
# print(A[[1,2]])
# print(A[[2,1]])

 All tests passed


In [108]:
A_test = np.array([
        [1, -2, 3, -4],
        [-5, 6, -7, 8],
        [-4, 3, -2, 1],
        [8, -7, 6, -5]
    ], dtype=np.dtype(float))
print("Original matrix:")
print(A_test)

print("\nOriginal matrix after its third row is multiplied by -2:")
print(MultiplyRow(A_test,2,-2))

print("\nOriginal matrix after exchange of the third row with the sum of itself and first row multiplied by 4:")
print(AddRow(A_test,0,2,4))

print("\nOriginal matrix after exchange of its first and third rows:")
print(SwapRows(A_test,0,2))

Original matrix:
[[ 1. -2.  3. -4.]
 [-5.  6. -7.  8.]
 [-4.  3. -2.  1.]
 [ 8. -7.  6. -5.]]

Original matrix after its third row is multiplied by -2:
[[ 1. -2.  3. -4.]
 [-5.  6. -7.  8.]
 [ 8. -6.  4. -2.]
 [ 8. -7.  6. -5.]]

Original matrix after exchange of the third row with the sum of itself and first row multiplied by 4:
[[  1.  -2.   3.  -4.]
 [ -5.   6.  -7.   8.]
 [  0.  -5.  10. -15.]
 [  8.  -7.   6.  -5.]]

Original matrix after exchange of its first and third rows:
[[-4.  3. -2.  1.]
 [-5.  6. -7.  8.]
 [ 1. -2.  3. -4.]
 [ 8. -7.  6. -5.]]


# Finding Solution to A



In [109]:
# def augmented_to_ref(A, b):
#   ### START CODE HERE ###
#   # stack horizontally matrix A and vector b, which needs to be reshaped as a vector (4, 1)
#   A_system = np.hstack((A, b.reshape((4, 1))))
#   # print(A_system)

#   A_ref = SwapRows(A_system, 0, 1)

#   # print(A_ref)

#   A_ref = AddRow(A_ref, 0, 1, -2)

#   A_ref = AddRow(A_ref, 0, 2, 1)
#   # print(A_ref)

#   A_ref = AddRow(A_ref, 0, 3, -1)
#   # print(A_ref)

#   A_ref = AddRow(A_ref, 2, 3, 1)
#   # print(A_ref)

#   A_ref = SwapRows(A_ref, 1, 3)
#   # print(A_ref)

#   A_ref = AddRow(A_ref, 2, 3, 1)
#   # print(A_ref)

#   A_ref = AddRow(A_ref, 1, 2, -4)
#   # print(A_ref)

#   A_ref = AddRow(A_ref, 1, 3, 1)
#   # print(A_ref)

#   A_ref = AddRow(A_ref, 3, 2, 2)
#   # print(A_ref)

#   A_ref = AddRow(A_ref, 2, 3, -8)

#   A_ref = MultiplyRow(A_ref, 3, -1/17)

#   return A_ref

# A_ref = augmented_to_ref(A, b)

# print(A_ref)

In [110]:
System_A = np.hstack((A,b.reshape(4,1)))
# print(System_A)

# Step 1 Making Row1 1st element as 1
A1 = SwapRows(System_A,0,1)

# print(A1)

# Making 1st column elemenet to 0 except row1

A2 = AddRow(A1,2,1,2)
# print(A2)

A2 = AddRow(A2,0,2,1)
# print(A2)

A2 = AddRow(A2,0,3,-1)
print(A2)

# Making next diagonal elements 1 and below elements 0

A3 = AddRow(A2,2,1,-1)
print(A3)

A3 = MultiplyRow(A3,1,-1)
print(A3)

A3 = AddRow(A3,1,2,-4)
A3 = AddRow(A3,1,3,3)
print(A3)

A3 = MultiplyRow(A3,2,1/17)
A3 = AddRow(A3,2,3,9)
print(A3)


A3 =  MultiplyRow(A3,3,-1)
print(A3)

# A3 = AddRow(A3,2,3,-8)
# # print(A3)


# A3 = MultiplyRow(A3,3,-1)
# print(A3)


[[ 1.  2. -1. -1.  3.]
 [ 0.  3.  5.  5. 34.]
 [ 0.  4.  1.  1. 17.]
 [ 0. -3.  3.  2.  5.]]
[[ 1.  2. -1. -1.  3.]
 [ 0. -1.  4.  4. 17.]
 [ 0.  4.  1.  1. 17.]
 [ 0. -3.  3.  2.  5.]]
[[  1.   2.  -1.  -1.   3.]
 [ -0.   1.  -4.  -4. -17.]
 [  0.   4.   1.   1.  17.]
 [  0.  -3.   3.   2.   5.]]
[[  1.   2.  -1.  -1.   3.]
 [ -0.   1.  -4.  -4. -17.]
 [  0.   0.  17.  17.  85.]
 [  0.   0.  -9. -10. -46.]]
[[  1.   2.  -1.  -1.   3.]
 [ -0.   1.  -4.  -4. -17.]
 [  0.   0.   1.   1.   5.]
 [  0.   0.   0.  -1.  -1.]]
[[  1.   2.  -1.  -1.   3.]
 [ -0.   1.  -4.  -4. -17.]
 [  0.   0.   1.   1.   5.]
 [ -0.  -0.  -0.   1.   1.]]


In [111]:
x3 = 1
x2 = A3[2,4]-A3[2,3]*x3
x1 = A3[1,4] - A3[1,3]*x3 - A3[1,2]*x2
x0 = A3[0,4] - A3[0,3]*x3 - A3[0,2]*x2 - A3[0,1]*x1
print(x0,x1,x2,x3)

2.0 3.0 4.0 1


In [112]:
test.test_solution_elimination(x0,x1,x2,x3)

 All tests passed


In [113]:
# Reducing to diagonal Matrix

A3 = AddRow(A3,3,2,-1)
A3 = AddRow(A3,3,1,4)
A3 = AddRow(A3,2,1,4)
A3 = AddRow(A3,3,0,1)
A3 = AddRow(A3,2,0,1)
A3 = AddRow(A3,1,0,-2)
print(A3)

[[ 1.  0.  0.  0.  2.]
 [ 0.  1.  0.  0.  3.]
 [ 0.  0.  1.  0.  4.]
 [-0. -0. -0.  1.  1.]]
